version: "3.8"

services:
  backend:
    build:
      context: ./backend-devsecops/
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend-devsecops/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend-devsecops/
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
